version: 0.0
os: linux
files:
  - source: /
    destination: /home/ubuntu/do_it_django_test
    file_exists_behavior: OVERWRITE

permissions:
  - object: /home/ubuntu
    pattern: '**'
    owner: root
    group: root

hooks:
  AfterInstall:
    - location: scripts/after_deploy.sh
      timeout: 100000  # 100초
      runas: root
